/**
 * Videos Database can be added here.
 * You can add videos of your wish with different attributes
 * https://image.tmdb.org/t/p/original/
 * */

export const videos = [
  {
    _id: "b1ce7adc-dc04-4cc9-9651-b2c1859976fb",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/xGrTm3J0FTafmuQ85vF7ZCw94x6.jpg",
    genre_ids: [18, 36, 12],
    id: 589761,
    original_language: "ru",
    original_title: "Чернобыль",
    overview:
      "The aftermath of a shocking explosion at the Chernobyl nuclear power station made hundreds of people sacrifice their lives to clean up the site of the catastrophe and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. This is their story.",
    popularity: 326.2,
    poster_path:
      "https://image.tmdb.org/t/p/original/AmJLuHjxPdIJO6vmymeWADG6jK5.jpg",
    release_date: "2021-04-15",
    title: "Chernobyl: Abyss",
    video: false,
    vote_average: 6.1,
    category: "Originals",
    vote_count: 355,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "a065ca1a-d2b8-4806-a4a2-ea1b3174a95a",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/lD8dFIk9wDEvOwZw0RB47e346io.jpg",
    genre_ids: [18, 36, 10749],
    id: 698508,
    original_language: "en",
    original_title: "Redeeming Love",
    overview:
      "A retelling of the biblical book of Hosea set against the backdrop of the California Gold Rush of 1850.",
    popularity: 410.977,
    poster_path:
      "https://image.tmdb.org/t/p/original/pDc2HxQtC0MlKD4QfRvmKREEyhc.jpg",
    release_date: "2022-01-21",
    title: "Redeeming Love",
    video: false,
    vote_average: 7.6,
    category: "Originals",
    vote_count: 47,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "38b2f1c3-ccf3-4054-a93c-493bcae7c5ae",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/v0zhVgtqisaFsSVAOKxqwVOOlQr.jpg",
    genre_ids: [28, 18, 36],
    id: 617653,
    original_language: "en",
    original_title: "The Last Duel",
    overview:
      "King Charles VI declares that Knight Jean de Carrouges settle his dispute with his squire, Jacques Le Gris, by challenging him to a duel.",
    popularity: 188.576,
    poster_path:
      "https://image.tmdb.org/t/p/original/zjrJE0fpzPvX8saJXj8VNfcjBoU.jpg",
    release_date: "2021-10-13",
    title: "The Last Duel",
    video: false,
    vote_average: 7.6,
    category: "Originals",
    vote_count: 2077,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "fd754a63-17cc-4e77-86ed-5cbb81236f37",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/rshlQ6LfPRSWFhpGL4s5ZkIPR51.jpg",
    genre_ids: [18, 36, 10752],
    id: 324786,
    original_language: "en",
    original_title: "Hacksaw Ridge",
    overview:
      "WWII American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first Conscientious Objector in American history to receive the Congressional Medal of Honor.",
    popularity: 181.331,
    poster_path:
      "https://image.tmdb.org/t/p/original/fTuxNlgEm04PPFkr1xfK94Jn8BW.jpg",
    release_date: "2016-10-07",
    title: "Hacksaw Ridge",
    video: false,
    vote_average: 8.2,
    category: "Originals",
    vote_count: 10890,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "6a801001-8311-4ad8-93a5-bf80d1d715fa",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/pwpw1veVNW2Sls5sGbA9mqMYN49.jpg",
    genre_ids: [28, 12, 35, 36],
    id: 591120,
    original_language: "ko",
    original_title: "해적: 도깨비 깃발",
    overview:
      "A gutsy crew of Joseon pirates and bandits battle stormy waters, puzzling clues and militant rivals in search of royal gold lost at sea.",
    popularity: 167.763,
    poster_path:
      "https://image.tmdb.org/t/p/original/50UQeTrUM7ErXzkvqCsV6EXcM3g.jpg",
    release_date: "2022-01-26",
    title: "The Pirates: The Last Royal Treasure",
    video: false,
    vote_average: 6.7,
    category: "Originals",
    vote_count: 88,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "ae2fdc0d-a948-411c-9b37-603a228d8f96",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/4EJSMQOM1bZPHvzqAQe87suBxdf.jpg",
    genre_ids: [10752, 36, 18],
    id: 885110,
    original_language: "en",
    original_title: "Amina",
    overview:
      "In 16th-century Zazzau, now Zaria, Nigeria, Amina must utilize her military skills and tactics to defend her family's kingdom. Based on a true story.",
    popularity: 161.671,
    poster_path:
      "https://image.tmdb.org/t/p/original/hMIQiwLpBfTfe3ZbRlNx4225Mgg.jpg",
    release_date: "2021-11-04",
    title: "Amina",
    video: false,
    vote_average: 6.5,
    category: "Originals",
    vote_count: 104,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "61a7caf0-6859-44ab-841a-11e6ad904daf",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/bnMKMhGJuvELSjRp8KpkuDsBDw2.jpg",
    genre_ids: [12, 36, 18],
    id: 836009,
    original_language: "en",
    original_title: "Against the Ice",
    overview:
      "In 1909, two explorers fight to survive after they're left behind while on a Denmark expedition in ice-covered Greenland.",
    popularity: 140.203,
    poster_path:
      "https://image.tmdb.org/t/p/original/6FSGYvPEhIx3ThOikGqHmKxeyNN.jpg",
    release_date: "2022-02-10",
    title: "Against the Ice",
    video: false,
    vote_average: 6.9,
    category: "Originals",
    vote_count: 272,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "086fb091-b216-4795-8289-0ebb7e0a1cc7",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/93xA62uLd5CwMOAs37eQ7vPc1iV.jpg",
    genre_ids: [10402, 18, 36],
    id: 424694,
    original_language: "en",
    original_title: "Bohemian Rhapsody",
    overview:
      "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
    popularity: 92.14,
    poster_path:
      "https://image.tmdb.org/t/p/original/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg",
    release_date: "2018-10-24",
    title: "Bohemian Rhapsody",
    video: false,
    vote_average: 8,
    category: "Originals",
    vote_count: 14599,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "28dc3891-bd4c-4815-87d4-1387bdf98ab7",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/o3U4733mGsmieBeqs4Sw2ze6n53.jpg",
    genre_ids: [14, 18, 10749, 36],
    id: 245842,
    original_language: "en",
    original_title: "The King's Daughter",
    overview:
      "King Louis XIV's quest for immortality leads him to capture and steal a mermaid's life force, a move that is further complicated by his illegitimate daughter's discovery of the creature.",
    popularity: 85.243,
    poster_path:
      "https://image.tmdb.org/t/p/original/nCRfr3eOlwH7wfxaz6cU1bhMR1W.jpg",
    release_date: "2022-01-21",
    title: "The King's Daughter",
    video: false,
    vote_average: 7.4,
    category: "Originals",
    vote_count: 505,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "f524fa94-86d7-4334-8062-e4dbfaf75671",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/4kb7uR1UmXa33U6GB6F9xckFlhn.jpg",
    genre_ids: [18, 36],
    id: 614917,
    original_language: "en",
    original_title: "King Richard",
    overview:
      "The story of how Richard Williams served as a coach to his daughters Venus and Serena, who will soon become two of the most legendary tennis players in history.",
    popularity: 103.634,
    poster_path:
      "https://image.tmdb.org/t/p/original/2dfujXrxePtYJPiPHj1HkAFQvpu.jpg",
    release_date: "2021-11-18",
    title: "King Richard",
    video: false,
    vote_average: 7.9,
    category: "Originals",
    vote_count: 1290,
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "58db81a4-d1f2-49da-96a0-5e1fd2da07ce",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/rl49Qr4KbfTSYjXYAN8fMDIt2xS.jpg",
    genre_ids: [28, 878, 14],
    id: 526896,
    original_language: "en",
    original_title: "Morbius",
    overview:
      "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
    poster_path:
      "https://image.tmdb.org/t/p/original/6JjfSchsU6daXk2AKX8EEBjO3Fm.jpg",
    release_date: "2022-03-30",
    title: "Morbius",
    video: false,
    vote_average: 6.3,
    vote_count: 938,
    popularity: 6323.965,
    media_type: "movie",
    category: "Trending",
  },
  {
    _id: "000d54cf-8d91-4a73-949e-8df5b2ffd86a",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/cqnVuxXe6vA7wfNWubak3x36DKJ.jpg",
    genre_ids: [28, 12, 14, 53],
    id: 639933,
    original_language: "en",
    original_title: "The Northman",
    poster_path:
      "https://image.tmdb.org/t/p/original/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg",
    title: "The Northman",
    video: false,
    vote_average: 7.5,
    overview:
      "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
    release_date: "2022-04-07",
    vote_count: 974,
    popularity: 5772.331,
    media_type: "movie",
    category: "Trending",
  },
  {
    _id: "bcc4a596-0d7a-48f2-8980-e20d0e9fe900",
    video: false,
    title: "The Batman",
    id: 414906,
    overview:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    release_date: "2022-03-01",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/xHrp2pq73oi9D64xigPjWW1wcz1.jpg",
    genre_ids: [80, 9648, 53],
    vote_count: 4672,
    original_language: "en",
    original_title: "The Batman",
    poster_path:
      "https://image.tmdb.org/t/p/original/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    vote_average: 7.8,
    popularity: 2950.956,
    media_type: "movie",
    category: "Trending",
  },
  {
    _id: "ef556857-8729-4aff-bb9c-e5942659d7ec",
    title: "The Lost City",
    video: false,
    vote_average: 6.8,
    overview:
      "A reclusive romance novelist who was sure nothing could be worse than getting stuck on a book tour with her cover model, until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.",
    release_date: "2022-03-24",
    id: 752623,
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg",
    genre_ids: [28, 12, 35, 10749],
    vote_count: 648,
    original_language: "en",
    original_title: "The Lost City",
    poster_path:
      "https://image.tmdb.org/t/p/original/neMZH82Stu91d3iqvLdNQfqPPyl.jpg",
    popularity: 8293.346,
    media_type: "movie",
    category: "Trending",
  },
  {
    _id: "693dcefa-cdbc-4c48-a25d-600277717a15",
    video: false,
    vote_average: 8.7,
    overview:
      "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
    id: 545611,
    title: "Everything Everywhere All at Once",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg",
    vote_count: 254,
    genre_ids: [28, 12, 878, 35],
    release_date: "2022-03-24",
    original_language: "en",
    original_title: "Everything Everywhere All at Once",
    poster_path:
      "https://image.tmdb.org/t/p/original/rKvCys0fMIIi1X9rmJBxTPLAtoU.jpg",
    popularity: 325.871,
    media_type: "movie",
    category: "Trending",
  },
  {
    _id: "16dfbc01-a547-45e8-b5c3-34082297eb05",
    first_air_date: "2022-03-30",
    backdrop_path:
      "https://image.tmdb.org/t/p/original/vfWdZYGR5505zrCdgTHteFyARu3.jpg",
    genre_ids: [10759, 10765, 9648],
    original_name: "Moon Knight",
    origin_country: ["US"],
    id: 92749,
    vote_count: 840,
    poster_path:
      "https://image.tmdb.org/t/p/original/YksR65as1ppF2N48TJAh2PLamX.jpg",
    vote_average: 8.3,
    overview:
      "When Steven Grant, a mild-mannered gift-shop employee, becomes plagued with blackouts and memories of another life, he discovers he has dissociative identity disorder and shares a body with mercenary Marc Spector. As Steven/Marc’s enemies converge upon them, they must navigate their complex identities while thrust into a deadly mystery among the powerful gods of Egypt.",
    name: "Moon Knight",
    original_language: "en",
    popularity: 2616.606,
    media_type: "tv",
    category: "Trending",
  },
  {
    _id: "3950b21d-af1d-4b3d-8bb6-17c5ee910287",
    vote_average: 8.7,
    overview:
      "Depicting an epic 26th-century conflict between humanity and an alien threat known as the Covenant, the series weaves deeply drawn personal stories with action, adventure and a richly imagined vision of the future.",
    name: "Halo",
    id: 52814,
    vote_count: 711,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/1qpUk27LVI9UoTS7S0EixUBj5aR.jpg",
    poster_path:
      "https://image.tmdb.org/t/p/original/eO0QV5qJaEngP1Ax9w3eV6bJG2f.jpg",
    genre_ids: [10759, 10765],
    first_air_date: "2022-03-24",
    original_language: "en",
    original_name: "Halo",
    origin_country: ["US"],
    popularity: 6176.562,
    media_type: "tv",
    category: "Trending",
  },
  {
    _id: "a930635d-9053-47fa-8d04-b04085ca5486",
    release_date: "2022-04-06",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/zGLHX92Gk96O1DJvLil7ObJTbaL.jpg",
    id: 338953,
    genre_ids: [28, 12, 14],
    original_language: "en",
    original_title: "Fantastic Beasts: The Secrets of Dumbledore",
    poster_path:
      "https://image.tmdb.org/t/p/original/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
    vote_count: 1062,
    video: false,
    vote_average: 6.7,
    title: "Fantastic Beasts: The Secrets of Dumbledore",
    overview:
      "Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald's growing legion of followers.",
    popularity: 787.576,
    media_type: "movie",
    category: "Trending",
  },
  {
    _id: "2b982b80-8ddb-491d-a0a9-8a517eab671d",
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    id: 634649,
    video: false,
    vote_average: 8.1,
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    vote_count: 12901,
    genre_ids: [28, 12, 878],
    poster_path:
      "https://image.tmdb.org/t/p/original/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    popularity: 2676.693,
    media_type: "movie",
    category: "Trending",
  },
  {
    _id: "002cdf69-1b35-4046-8d90-b5dd8104be5c",
    poster_path:
      "https://image.tmdb.org/t/p/original/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
    id: 629542,
    vote_average: 7.8,
    overview:
      "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
    release_date: "2022-03-17",
    title: "The Bad Guys",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/fEe5fe82qHzjO4yej0o79etqsWV.jpg",
    vote_count: 450,
    genre_ids: [16, 35, 28, 10751, 80],
    video: false,
    original_language: "en",
    original_title: "The Bad Guys",
    popularity: 2622.506,
    media_type: "movie",
    category: "Trending",
  },
  {
    _id: "4d60ad18-f326-4203-bc94-45599208c8f4",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
    genre_ids: [28, 878, 35, 10751, 12],
    id: 675353,
    original_language: "en",
    original_title: "Sonic the Hedgehog 2",
    overview:
      "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
    popularity: 12851.144,
    poster_path:
      "https://image.tmdb.org/t/p/original/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    release_date: "2022-03-30",
    title: "Sonic the Hedgehog 2",
    video: false,
    vote_average: 7.7,
    vote_count: 1142,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "cd8c1c60-7b82-4e4c-b39f-7fa1ff77b047",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/AdyJH8kDm8xT8IKTlgpEC15ny4u.jpg",
    genre_ids: [14, 28, 12],
    id: 453395,
    original_language: "en",
    original_title: "Doctor Strange in the Multiverse of Madness",
    overview:
      "Doctor Strange, with the help of mystical allies both old and new, traverses the mind-bending and dangerous alternate realities of the Multiverse to confront a mysterious new adversary.",
    popularity: 5007.839,
    poster_path:
      "https://image.tmdb.org/t/p/original/wRnbWt44nKjsFPrqSmwYki5vZtF.jpg",
    release_date: "2022-05-04",
    title: "Doctor Strange in the Multiverse of Madness",
    video: false,
    vote_average: 7.5,
    vote_count: 1139,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "90d14150-b10b-4ba8-ad0e-64da32c848c3",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/fEe5fe82qHzjO4yej0o79etqsWV.jpg",
    genre_ids: [16, 35, 28, 10751, 80],
    id: 629542,
    original_language: "en",
    original_title: "The Bad Guys",
    overview:
      "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
    popularity: 4730.107,
    poster_path:
      "https://image.tmdb.org/t/p/original/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
    release_date: "2022-03-17",
    title: "The Bad Guys",
    video: false,
    vote_average: 7.7,
    vote_count: 305,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "1deee6fb-2750-496a-a0b8-9aa5aa7fd652",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/aEGiJJP91HsKVTEPy1HhmN0wRLm.jpg",
    genre_ids: [28, 12],
    id: 335787,
    original_language: "en",
    original_title: "Uncharted",
    overview:
      "A young street-smart, Nathan Drake and his wisecracking partner Victor “Sully” Sullivan embark on a dangerous pursuit of “the greatest treasure never found” while also tracking clues that may lead to Nathan’s long-lost brother.",
    popularity: 4449.169,
    poster_path:
      "https://image.tmdb.org/t/p/original/tlZpSxYuBRoVJBOpUrPdQe9FmFq.jpg",
    release_date: "2022-02-10",
    title: "Uncharted",
    video: false,
    vote_average: 7.2,
    vote_count: 1796,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "32b4622d-19ae-45aa-bf21-53bc5b3aa8f3",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    genre_ids: [28, 12, 878],
    id: 634649,
    original_language: "en",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.",
    popularity: 3933.964,
    poster_path:
      "https://image.tmdb.org/t/p/original/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    release_date: "2021-12-15",
    title: "Spider-Man: No Way Home",
    video: false,
    vote_average: 8.1,
    vote_count: 12602,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "0b126af7-d5ea-458e-9617-467cfd0875f2",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/eQN31P4IEhyp6NkdccvppJnyuJ4.jpg",
    genre_ids: [28, 12, 14, 878],
    id: 284052,
    original_language: "en",
    original_title: "Doctor Strange",
    overview:
      "After his career is destroyed, a brilliant but arrogant surgeon gets a new lease on life when a sorcerer takes him under her wing and trains him to defend the world against evil.",
    popularity: 2807.025,
    poster_path:
      "https://image.tmdb.org/t/p/original/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg",
    release_date: "2016-10-25",
    title: "Doctor Strange",
    video: false,
    vote_average: 7.4,
    vote_count: 18894,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "24b14079-084d-412d-837d-dd31cdb417d3",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/192vHmAPbk5esL34XMKZ1YLGFjr.jpg",
    genre_ids: [28, 53, 80],
    id: 763285,
    original_language: "en",
    original_title: "Ambulance",
    overview:
      "Decorated veteran Will Sharp, desperate for money to cover his wife's medical bills, asks for help from his adoptive brother Danny. A charismatic career criminal, Danny instead offers him a score: the biggest bank heist in Los Angeles history: $32 million.",
    popularity: 2670.696,
    poster_path:
      "https://image.tmdb.org/t/p/original/kuxjMVuc3VTD7p42TZpJNsSrM1V.jpg",
    release_date: "2022-03-16",
    title: "Ambulance",
    video: false,
    vote_average: 7,
    vote_count: 515,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "95bd6f52-7984-4cf2-affa-5de77a17d375",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/x747ZvF0CcYYTTpPRCoUrxA2cYy.jpg",
    genre_ids: [878, 12, 28],
    id: 406759,
    original_language: "en",
    original_title: "Moonfall",
    overview:
      "A mysterious force knocks the moon from its orbit around Earth and sends it hurtling on a collision course with life as we know it.",
    popularity: 2231.435,
    poster_path:
      "https://image.tmdb.org/t/p/original/odVv1sqVs0KxBXiA8bhIBlPgalx.jpg",
    release_date: "2022-02-03",
    title: "Moonfall",
    video: false,
    vote_average: 6.5,
    vote_count: 935,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "ea1f7821-9da0-4ff6-a04a-29ad4aaf3994",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/xzLOQjF1w4og963lxsGJwMhPbZ.jpg",
    genre_ids: [28, 80, 18],
    id: 951470,
    original_language: "en",
    original_title: "Silverton Siege",
    overview:
      "After a failed sabotage mission, a trio of anti-apartheid freedom fighters ends up in a tense bank hostage situation. Based on a true story.",
    popularity: 1226.236,
    poster_path:
      "https://image.tmdb.org/t/p/original/5HruMN0vvl84AqD7sCDXFNO4RhP.jpg",
    release_date: "2022-04-27",
    title: "Silverton Siege",
    video: false,
    vote_average: 6.3,
    vote_count: 46,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "9dbefb5a-7d56-4edf-8ef4-193db7d917dc",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/xicKILMzPn6XZYCOpWwaxlUzg6S.jpg",
    genre_ids: [53, 28],
    id: 294793,
    original_language: "en",
    original_title: "All the Old Knives",
    overview:
      "When the CIA discovers one of its agents leaked information that cost more than 100 people their lives, veteran operative Henry Pelham is assigned to root out the mole with his former lover and colleague Celia Harrison.",
    popularity: 1062.699,
    poster_path:
      "https://image.tmdb.org/t/p/original/g4tMniKxol1TBJrHlAtiDjjlx4Q.jpg",
    release_date: "2022-04-08",
    title: "All the Old Knives",
    video: false,
    vote_average: 6,
    vote_count: 206,
    category: "Action",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "5e9d1f2d-f15f-476d-9772-822d39a737d4",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/wPU78OPN4BYEgWYdXyg0phMee64.jpg",
    genre_ids: [18, 80],
    id: 278,
    original_language: "en",
    original_title: "The Shawshank Redemption",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    popularity: 63.775,
    poster_path:
      "https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    release_date: "1994-09-23",
    title: "The Shawshank Redemption",
    video: false,
    vote_average: 8.7,
    vote_count: 21370,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "aab1fc24-e9d8-4b97-b960-3369ddb0f25c",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg",
    genre_ids: [35, 18, 10749],
    id: 19404,
    original_language: "hi",
    original_title: "दिलवाले दुल्हनिया ले जायेंगे",
    overview:
      "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
    popularity: 18.436,
    poster_path:
      "https://image.tmdb.org/t/p/original/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
    release_date: "1995-10-20",
    title: "Dilwale Dulhania Le Jayenge",
    video: false,
    vote_average: 8.7,
    vote_count: 3619,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "179c2ee9-3397-4b04-b378-be75d7007fee",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/AbgEQO2mneCSOc8CSnOMa8pBS8I.jpg",
    genre_ids: [18, 80],
    id: 238,
    original_language: "en",
    original_title: "The Godfather",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    popularity: 65.284,
    poster_path:
      "https://image.tmdb.org/t/p/original/n6PvMAKL66gavIFxOyRB6czAeQO.jpg",
    release_date: "1972-03-14",
    title: "The Godfather",
    video: false,
    vote_average: 8.7,
    vote_count: 15927,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "6c484017-0427-4265-bc0f-e9724da7d5b2",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/ryr532va3rN7MADPAO2updA4Akz.jpg",
    genre_ids: [10751, 18],
    id: 667257,
    original_language: "es",
    original_title: "Cosas imposibles",
    overview:
      "A widow who is tormented by the memory of her abusive husband befriends a young man.",
    popularity: 23.371,
    poster_path:
      "https://image.tmdb.org/t/p/original/eaf7GQj0ieOwm08rrvjJQNbN0kN.jpg",
    release_date: "2021-06-17",
    title: "Impossible Things",
    video: false,
    vote_average: 8.7,
    vote_count: 227,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "39db3ddb-637f-4fe8-8da6-0445b39a7c0d",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg",
    genre_ids: [18, 36, 10752],
    id: 424,
    original_language: "en",
    original_title: "Schindler's List",
    overview:
      "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
    popularity: 36.472,
    poster_path:
      "https://image.tmdb.org/t/p/original/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    release_date: "1993-11-30",
    title: "Schindler's List",
    video: false,
    vote_average: 8.6,
    vote_count: 12730,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "1fe3cd93-fdb8-406d-8bfb-4e16acdd90ee",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/v5CEt88iDsuoMaW1Q5Msu9UZdEt.jpg",
    genre_ids: [10749, 18],
    id: 730154,
    original_language: "ja",
    original_title: "きみの瞳が問いかけている",
    overview:
      "A tragic accident lead to Kaori's blindness, but she clings to life and the smaller pleasures it can still afford her. She meets Rui and begins to talk to him. Rui was once a promising kickboxer, but something happened in his past. Kaori's smile brings out a change in Rui. However, the two are connected in more than one way. Rui attempts to do what is right.",
    popularity: 55.491,
    poster_path:
      "https://image.tmdb.org/t/p/original/cVn8E3Fxbi8HzYYtaSfsblYC4gl.jpg",
    release_date: "2020-10-23",
    title: "Your Eyes Tell",
    video: false,
    vote_average: 8.6,
    vote_count: 303,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "159d3dc9-6212-4ed5-9750-8526437322b3",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/poec6RqOKY9iSiIUmfyfPfiLtvB.jpg",
    genre_ids: [18, 80],
    id: 240,
    original_language: "en",
    original_title: "The Godfather: Part II",
    overview:
      "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
    popularity: 52.23,
    poster_path:
      "https://image.tmdb.org/t/p/original/bMadFzhjy9T7R8J48QGq1ngWNAK.jpg",
    release_date: "1974-12-20",
    title: "The Godfather: Part II",
    video: false,
    vote_average: 8.6,
    vote_count: 9604,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "4f3c4cd7-36ce-494f-a0b1-1c753929f927",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/3RMLbSEXOn1CzLoNT7xFeLfdxhq.jpg",
    genre_ids: [10749, 16],
    id: 372754,
    original_language: "ja",
    original_title: "同級生",
    overview:
      "Rihito Sajo, an honor student with a perfect score on the entrance exam and Hikaru Kusakabe, in a band and popular among girls, would have never crossed paths. Until one day they started talking at the practice for their school’s upcoming chorus festival. After school, the two meet regularly, as Hikaru helps Rihito to improve his singing skills. While they listen to each other’s voice and harmonize, their hearts start to beat together.",
    popularity: 9.154,
    poster_path:
      "https://image.tmdb.org/t/p/original/cIfRCA5wEvj9tApca4UDUagQEiM.jpg",
    release_date: "2016-02-20",
    title: "Dou kyu sei – Classmates",
    video: false,
    vote_average: 8.6,
    vote_count: 224,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "26a09768-25a4-499a-a75b-8ea57d787903",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/jtAI6OJIWLWiRItNSZoWjrsUtmi.jpg",
    genre_ids: [10749],
    id: 724089,
    original_language: "en",
    original_title: "Gabriel's Inferno: Part II",
    overview:
      "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
    popularity: 17.855,
    poster_path:
      "https://image.tmdb.org/t/p/original/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
    release_date: "2020-07-31",
    title: "Gabriel's Inferno: Part II",
    video: false,
    vote_average: 8.6,
    vote_count: 1404,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "107d0874-e72c-49ec-aa70-2a9063a5bc44",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/lp6SmwyNRspEYkkLXFEVuNlCw77.jpg",
    genre_ids: [16, 14, 10749, 18],
    id: 533514,
    original_language: "ja",
    original_title: "劇場版 ヴァイオレット・エヴァーガーデン",
    overview:
      "As the world moves on from the war and technological advances bring changes to her life, Violet still hopes to see her lost commanding officer again.",
    popularity: 17.74,
    poster_path:
      "https://image.tmdb.org/t/p/original/bajajkoErDst0JxdFyBkABiF9rW.jpg",
    release_date: "2020-09-18",
    title: "Violet Evergarden: The Movie",
    video: false,
    vote_average: 8.6,
    vote_count: 221,
    category: "Top Rated",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "52619305-d157-4b51-a37a-4e2aee0f069d",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/i0zbSmiyyylh7H3Qb4jgscz46Pm.jpg",
    genre_ids: [27],
    id: 893370,
    original_language: "es",
    original_title: "Virus-32",
    overview:
      "A virus is unleashed and a chilling massacre runs through the streets of Montevideo.",
    popularity: 1961.188,
    poster_path:
      "https://image.tmdb.org/t/p/original/wZiF79hbhLK1U2Pj9bF67NAKXQR.jpg",
    release_date: "2022-04-21",
    title: "Virus:32",
    video: false,
    vote_average: 6.7,
    vote_count: 36,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "080b530f-c89a-4051-947e-006c398015c8",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/An1nKjXahrChfEbZ3MAE8fsiut1.jpg",
    genre_ids: [27],
    id: 661791,
    original_language: "es",
    original_title: "La abuela",
    overview:
      "A Paris model must return to Madrid where her grandmother, who raised her, has had a stroke. But spending just a few days with this relative turns into an unexpected nightmare.",
    popularity: 934.942,
    poster_path:
      "https://image.tmdb.org/t/p/original/eIUixNvox4U4foL5Z9KbN9HXYSM.jpg",
    release_date: "2022-01-28",
    title: "The Grandmother",
    video: false,
    vote_average: 6,
    vote_count: 153,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "bed4a6ce-3aa0-4b9b-8c7d-1765814faca1",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/u5lEdCvKLkm1EhfQt3qe8Rr5DvR.jpg",
    genre_ids: [27],
    id: 938596,
    original_language: "en",
    original_title: "Bull Shark",
    overview:
      "A hungry shark begins feeding on unsuspecting lake goers in a small Texas town.",
    popularity: 632.569,
    poster_path:
      "https://image.tmdb.org/t/p/original/wGE4ImqYjJZQi3xFu4I2OLm8m0w.jpg",
    release_date: "2022-02-05",
    title: "Bull Shark",
    video: false,
    vote_average: 5.6,
    vote_count: 18,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "b2481aa8-376c-4a1f-b72a-efb1f870e0ec",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/33wnBK5NxvuKQv0Cxo3wMv0eR7F.jpg",
    genre_ids: [27, 53],
    id: 833425,
    original_language: "en",
    original_title: "No Exit",
    overview:
      "Stranded at a rest stop in the mountains during a blizzard, a recovering addict discovers a kidnapped child hidden in a car belonging to one of the people inside the building which sets her on a terrifying struggle to identify who among them is the kidnapper.",
    popularity: 659.336,
    poster_path:
      "https://image.tmdb.org/t/p/original/5cnLoWq9o5tuLe1Zq4BTX4LwZ2B.jpg",
    release_date: "2022-02-25",
    title: "No Exit",
    video: false,
    vote_average: 6.7,
    vote_count: 433,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "a37e2bde-91e1-4e23-aef5-2143c1c19ac9",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/xHRabofjmMGoIV3mb6xgy4nwOcS.jpg",
    genre_ids: [27],
    id: 801071,
    original_language: "en",
    original_title: "The Jack in the Box: Awakening",
    overview:
      "When a vintage Jack-in-the-box is opened by a dying woman, she enters into a deal with the demon within that would see her illness cured in return for helping it claim six innocent victims.",
    popularity: 591.248,
    poster_path:
      "https://image.tmdb.org/t/p/original/3Ib8vlWTrAKRrTWUrTrZPOMW4jp.jpg",
    release_date: "2022-02-24",
    title: "The Jack in the Box: Awakening",
    video: false,
    vote_average: 6.2,
    vote_count: 40,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "c7874e2b-3501-4e72-a76c-1835fd935195",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/o76ZDm8PS9791XiuieNB93UZcRV.jpg",
    genre_ids: [27, 28, 878],
    id: 460458,
    original_language: "en",
    original_title: "Resident Evil: Welcome to Raccoon City",
    overview:
      "Once the booming home of pharmaceutical giant Umbrella Corporation, Raccoon City is now a dying Midwestern town. The company’s exodus left the city a wasteland…with great evil brewing below the surface. When that evil is unleashed, the townspeople are forever…changed…and a small group of survivors must work together to uncover the truth behind Umbrella and make it through the night.",
    popularity: 533.126,
    poster_path:
      "https://image.tmdb.org/t/p/original/7uRbWOXxpWDMtnsd2PF3clu65jc.jpg",
    release_date: "2021-11-24",
    title: "Resident Evil: Welcome to Raccoon City",
    video: false,
    vote_average: 6.2,
    vote_count: 1525,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "904ce94e-c2ae-447d-ac74-355db8ab0f2c",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
    genre_ids: [27, 9648, 53],
    id: 646385,
    original_language: "en",
    original_title: "Scream",
    overview:
      "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
    popularity: 507.025,
    poster_path:
      "https://image.tmdb.org/t/p/original/1m3W6cpgwuIyjtg5nSnPx7yFkXW.jpg",
    release_date: "2022-01-12",
    title: "Scream",
    video: false,
    vote_average: 6.8,
    vote_count: 1254,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "c5e2a290-9c1e-4a1b-b4e3-799140f2645d",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/aTSA5zMWlVFTYBIZxTCMbLkfOtb.jpg",
    genre_ids: [27, 53],
    id: 632727,
    original_language: "en",
    original_title: "Texas Chainsaw Massacre",
    overview:
      "In this sequel, influencers looking to breathe new life into a Texas ghost town encounter Leatherface, an infamous killer who wears a mask of human skin.",
    popularity: 415.792,
    poster_path:
      "https://image.tmdb.org/t/p/original/meRIRfADEGVo65xgPO6eZvJ0CRG.jpg",
    release_date: "2022-02-18",
    title: "Texas Chainsaw Massacre",
    video: false,
    vote_average: 5.1,
    vote_count: 735,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "efa793c3-a709-4a2a-ba7b-6f0abae85771",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/hk4PwhKhT7q7jp1lvA8aiYqDluy.jpg",
    genre_ids: [16, 18, 35, 27],
    id: 926899,
    original_language: "en",
    original_title: "The House",
    overview:
      "Across different eras, a poor family, an anxious developer and a fed-up landlady become tied to the same mysterious house in this animated dark comedy.",
    popularity: 381.166,
    poster_path:
      "https://image.tmdb.org/t/p/original/iZjMFSKCrleKolC1gYcz5Rs8bk1.jpg",
    release_date: "2022-01-14",
    title: "The House",
    video: false,
    vote_average: 7,
    vote_count: 579,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "0026396b-e9bb-4095-a57e-e05be8847a9c",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/5UANdP8xXHyVOGknfJlzQ7muLj3.jpg",
    genre_ids: [27],
    id: 829358,
    original_language: "en",
    original_title: "Queen of Spades",
    overview:
      "According to legend, an ominous entity known as the Queen of Spades can be summoned by performing an ancient ritual. Four teenagers summon the Queen of Spades, but they could never imagine the horrors that await them.",
    popularity: 319.08,
    poster_path:
      "https://image.tmdb.org/t/p/original/4IKBzVBPLXu9p5cfEfdJjHdlafV.jpg",
    release_date: "2021-06-11",
    title: "Queen of Spades",
    video: false,
    vote_average: 6.3,
    vote_count: 51,
    category: "Horror",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "18c0478f-8040-4836-a683-52d2c4009bc9",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
    genre_ids: [28, 878, 35, 10751, 12],
    id: 675353,
    original_language: "en",
    original_title: "Sonic the Hedgehog 2",
    overview:
      "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
    popularity: 12851.144,
    poster_path:
      "https://image.tmdb.org/t/p/original/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
    release_date: "2022-03-30",
    title: "Sonic the Hedgehog 2",
    video: false,
    vote_average: 7.7,
    vote_count: 1142,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "8cfca008-79b3-4238-84a9-28db2c54e4d3",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/fEe5fe82qHzjO4yej0o79etqsWV.jpg",
    genre_ids: [16, 35, 28, 10751, 80],
    id: 629542,
    original_language: "en",
    original_title: "The Bad Guys",
    overview:
      "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
    popularity: 4730.107,
    poster_path:
      "https://image.tmdb.org/t/p/original/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
    release_date: "2022-03-17",
    title: "The Bad Guys",
    video: false,
    vote_average: 7.7,
    vote_count: 305,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "60bc0a21-a23b-4adb-a9a6-fd40167405bd",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
    genre_ids: [16, 10751, 35, 14],
    id: 508947,
    original_language: "en",
    original_title: "Turning Red",
    overview:
      "Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.",
    popularity: 2493.062,
    poster_path:
      "https://image.tmdb.org/t/p/original/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg",
    release_date: "2022-03-10",
    title: "Turning Red",
    video: false,
    vote_average: 7.4,
    vote_count: 2058,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "4569a78b-70d3-4b05-8049-81d61423e661",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/3G1Q5xF40HkUBJXxt2DQgQzKTp5.jpg",
    genre_ids: [16, 35, 10751, 14],
    id: 568124,
    original_language: "en",
    original_title: "Encanto",
    overview:
      "The tale of an extraordinary family, the Madrigals, who live hidden in the mountains of Colombia, in a magical house, in a vibrant town, in a wondrous, charmed place called an Encanto. The magic of the Encanto has blessed every child in the family with a unique gift from super strength to the power to heal—every child except one, Mirabel. But when she discovers that the magic surrounding the Encanto is in danger, Mirabel decides that she, the only ordinary Madrigal, might just be her exceptional family's last hope.",
    popularity: 1174.064,
    poster_path:
      "https://image.tmdb.org/t/p/original/4j0PNHkMr5ax3IA8tjtxcmPU3QT.jpg",
    release_date: "2021-11-24",
    title: "Encanto",
    video: false,
    vote_average: 7.7,
    vote_count: 6357,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "6936cf5b-8c4d-428b-b1f9-4dcc9173825d",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/j8ve0iuDEnrcSpUxL62uvI4wnwB.jpg",
    genre_ids: [35, 10751, 10749],
    id: 937337,
    original_language: "es",
    original_title: "¡Qué despadre!",
    overview:
      "Pedro is a single man in his forties who likes to party, has no children and lives at night. Everything changes when he meets Alin. She mentions to him that she is looking for her dad and that there is a high probability that it is him.",
    popularity: 1065.468,
    poster_path:
      "https://image.tmdb.org/t/p/original/IkdBm3dDA11pNFlbkLcU5WdESn.jpg",
    release_date: "2022-02-09",
    title: "¡Qué despadre!",
    video: false,
    vote_average: 8,
    vote_count: 26,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "5bbda9aa-040a-4601-889d-826fdd08da83",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/tq3klWQevRK0Or0cGhsw0h3FDWQ.jpg",
    genre_ids: [12, 16, 35, 10751, 14],
    id: 676705,
    original_language: "fr",
    original_title: "Pil",
    overview:
      "Pil, a little vagabond girl, lives on the streets of the medieval city of Roc-en-Brume, along with her three tame weasels. She survives of food stolen from the castle of the sinister Regent Tristain. One day, to escape his guards, Pil disguises herself as a princess. Thus she embarks upon a mad, delirious adventure, together with Crobar, a big clumsy guard who thinks she's a noble, and Rigolin, a young crackpot jester. Pil is going to have to save Roland, rightful heir to the throne under the curse of a spell. This adventure will turn the entire kingdom upside down, and teach Pil that nobility can be found in all of us.",
    popularity: 982.846,
    poster_path:
      "https://image.tmdb.org/t/p/original/abPQVYyNfVuGoFUfGVhlNecu0QG.jpg",
    release_date: "2021-08-11",
    title: "Pil's Adventures",
    video: false,
    vote_average: 6.9,
    vote_count: 78,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "3869c441-8e04-475d-9997-6350300ebefb",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/qBLEWvJNVsehJkEJqIigPsWyBse.jpg",
    genre_ids: [16, 10751, 14, 35, 12],
    id: 585083,
    original_language: "en",
    original_title: "Hotel Transylvania: Transformania",
    overview:
      "When Van Helsing's mysterious invention, the \"Monsterfication Ray,\" goes haywire, Drac and his monster pals are all transformed into humans, and Johnny becomes a monster. In their new mismatched bodies, Drac and Johnny must team up and race across the globe to find a cure before it's too late, and before they drive each other crazy.",
    popularity: 914.217,
    poster_path:
      "https://image.tmdb.org/t/p/original/teCy1egGQa0y8ULJvlrDHQKnxBL.jpg",
    release_date: "2022-02-25",
    title: "Hotel Transylvania: Transformania",
    video: false,
    vote_average: 7.1,
    vote_count: 832,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "4ca57189-46cd-455b-b6b7-5dc30b54dd51",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/ewUqXnwiRLhgmGhuksOdLgh49Ch.jpg",
    genre_ids: [28, 12, 35, 878],
    id: 696806,
    original_language: "en",
    original_title: "The Adam Project",
    overview:
      "After accidentally crash-landing in 2022, time-traveling fighter pilot Adam Reed teams up with his 12-year-old self on a mission to save the future.",
    popularity: 919.599,
    poster_path:
      "https://image.tmdb.org/t/p/original/wFjboE0aFZNbVOF05fzrka9Fqyx.jpg",
    release_date: "2022-03-11",
    title: "The Adam Project",
    video: false,
    vote_average: 7,
    vote_count: 2119,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "2a43777f-358e-4d56-b7c5-d7c7d4708796",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/eG0oOQVsniPAuecPzDD1B1gnYWy.jpg",
    genre_ids: [16, 35, 12, 10751],
    id: 774825,
    original_language: "en",
    original_title: "The Ice Age Adventures of Buck Wild",
    overview:
      "The fearless one-eyed weasel Buck teams up with mischievous possum brothers Crash & Eddie as they head off on a new adventure into Buck's home: The Dinosaur World.",
    popularity: 815.451,
    poster_path:
      "https://image.tmdb.org/t/p/original/zzXFM4FKDG7l1ufrAkwQYv2xvnh.jpg",
    release_date: "2022-01-28",
    title: "The Ice Age Adventures of Buck Wild",
    video: false,
    vote_average: 6.9,
    vote_count: 1099,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "d63be8f8-797c-419d-8c77-5ff89f106547",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg",
    genre_ids: [28, 878, 35, 10751],
    id: 454626,
    original_language: "en",
    original_title: "Sonic the Hedgehog",
    overview:
      "Powered with incredible speed, Sonic The Hedgehog embraces his new home on Earth. That is, until Sonic sparks the attention of super-uncool evil genius Dr. Robotnik. Now it’s super-villain vs. super-sonic in an all-out race across the globe to stop Robotnik from using Sonic’s unique power for world domination.",
    popularity: 643.312,
    poster_path:
      "https://image.tmdb.org/t/p/original/aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
    release_date: "2020-02-12",
    title: "Sonic the Hedgehog",
    video: false,
    vote_average: 7.4,
    vote_count: 7934,
    category: "Comedy",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "1cf3b640-0082-40fd-bc55-960ae7dd7151",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/t9hNIUFcy0tYu55IPxjxRTTdZ6X.jpg",
    genre_ids: [10749, 18],
    id: 829557,
    original_language: "pl",
    original_title: "365 Days: This Day",
    overview:
      "Laura and Massimo are back and hotter than ever. But the reunited couple's new beginning is complicated by Massimo’s family ties and a mysterious man who enters Laura’s life to win her heart and trust, at any cost.",
    popularity: 1823.374,
    poster_path:
      "https://image.tmdb.org/t/p/original/7qU0SOVcQ8BTJLodcAlulUAG16C.jpg",
    release_date: "2022-04-27",
    title: "365 Days: This Day",
    video: false,
    vote_average: 5.7,
    vote_count: 346,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "c40906b8-5047-43d0-8fd6-700b5b81ef76",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/j8ve0iuDEnrcSpUxL62uvI4wnwB.jpg",
    genre_ids: [35, 10751, 10749],
    id: 937337,
    original_language: "es",
    original_title: "¡Qué despadre!",
    overview:
      "Pedro is a single man in his forties who likes to party, has no children and lives at night. Everything changes when he meets Alin. She mentions to him that she is looking for her dad and that there is a high probability that it is him.",
    popularity: 1065.468,
    poster_path:
      "https://image.tmdb.org/t/p/original/IkdBm3dDA11pNFlbkLcU5WdESn.jpg",
    release_date: "2022-02-09",
    title: "¡Qué despadre!",
    video: false,
    vote_average: 8,
    vote_count: 26,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "bc24f930-65ad-4d8e-9b51-5eadf5e501be",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/vrNKZrPscucCO5SnHEpp5DZ7QWx.jpg",
    genre_ids: [35, 10749],
    id: 860159,
    original_language: "en",
    original_title: "Crush",
    overview:
      "When an aspiring young artist is forced to join her high school track team, she uses it as an opportunity to pursue the girl she's been harboring a long-time crush on. But she soon finds herself falling for an unexpected teammate and discovers what real love feels like.",
    popularity: 598.079,
    poster_path:
      "https://image.tmdb.org/t/p/original/hayr56csDzCSADaejgrRMVPHyDy.jpg",
    release_date: "2022-04-29",
    title: "Crush",
    video: false,
    vote_average: 7.4,
    vote_count: 68,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "02954c3e-2be1-41a9-9fa4-be4cccf9981e",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/i9rEpTqC6aIQOWOc4PDEEAE3hFe.jpg",
    genre_ids: [10749, 878, 18],
    id: 818750,
    original_language: "en",
    original_title: "The In Between",
    overview:
      "After surviving a car accident that took the life of her boyfriend, a teenage girl believes he's attempting to reconnect with her from the after world.",
    popularity: 468.575,
    poster_path:
      "https://image.tmdb.org/t/p/original/7RcyjraM1cB1Uxy2W9ZWrab4KCw.jpg",
    release_date: "2022-02-11",
    title: "The In Between",
    video: false,
    vote_average: 7,
    vote_count: 255,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "e15c2766-9f02-424e-adbd-d17f65677794",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/A3bsT0m1um6tvcmlIGxBwx9eAxn.jpg",
    genre_ids: [12, 35, 10749],
    id: 752623,
    original_language: "en",
    original_title: "The Lost City",
    overview:
      "Follows a reclusive romance novelist who was sure nothing could be worse than getting stuck on a book tour with her cover model, until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.",
    popularity: 505.424,
    poster_path:
      "https://image.tmdb.org/t/p/original/neMZH82Stu91d3iqvLdNQfqPPyl.jpg",
    release_date: "2022-03-24",
    title: "The Lost City",
    video: false,
    vote_average: 6.9,
    vote_count: 292,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "75f69484-3dad-420c-bd02-f3dc0142b76a",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/4rsomWxlqnHt3muGYK06auhOib6.jpg",
    genre_ids: [10749, 18],
    id: 818647,
    original_language: "es",
    original_title: "A través de mi ventana",
    overview:
      "Raquel's longtime crush on her next-door neighbor turns into something more when he starts developing feelings for her, despite his family's objections.",
    popularity: 301.721,
    poster_path:
      "https://image.tmdb.org/t/p/original/6gg7fvKc1ZxP9yCczweSxIGYp4S.jpg",
    release_date: "2022-02-04",
    title: "Through My Window",
    video: false,
    vote_average: 7.6,
    vote_count: 1779,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "95ea40a7-53be-4780-90d0-abd19deb9ef2",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/sqLNgWTMBhLBRY26SwwfWcSI5qq.jpg",
    genre_ids: [35, 10749],
    id: 803104,
    original_language: "en",
    original_title: "Sex Appeal",
    overview:
      "Avery, a teenager with a tendency towards perfectionism, enlists her friend Larson to help her prepare for her first time with her long-distance boyfriend.",
    popularity: 286.535,
    poster_path:
      "https://image.tmdb.org/t/p/original/mpwXOeSSQdBjUpyQqf6YHYbSTFO.jpg",
    release_date: "2022-01-14",
    title: "Sex Appeal",
    video: false,
    vote_average: 6.7,
    vote_count: 81,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "8ba8eeb3-f3c5-44bd-9afe-ec8d941c1ecb",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/lD8dFIk9wDEvOwZw0RB47e346io.jpg",
    genre_ids: [18, 36, 10749],
    id: 698508,
    original_language: "en",
    original_title: "Redeeming Love",
    overview:
      "A retelling of the biblical book of Hosea set against the backdrop of the California Gold Rush of 1850.",
    popularity: 410.977,
    poster_path:
      "https://image.tmdb.org/t/p/original/pDc2HxQtC0MlKD4QfRvmKREEyhc.jpg",
    release_date: "2022-01-21",
    title: "Redeeming Love",
    video: false,
    vote_average: 7.6,
    vote_count: 47,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "5d2eff0e-47ae-46b9-896d-2cb073ea17d6",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/lV3UFPPxDIPelh46G9oySXN9Mcz.jpg",
    genre_ids: [10749, 18],
    id: 744275,
    original_language: "en",
    original_title: "After We Fell",
    overview:
      "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
    popularity: 265.182,
    poster_path:
      "https://image.tmdb.org/t/p/original/dU4HfnTEJDf9KvxGS9hgO7BVeju.jpg",
    release_date: "2021-09-01",
    title: "After We Fell",
    video: false,
    vote_average: 7.1,
    vote_count: 1686,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "4129528d-55ff-4a42-85e4-0cd53d56524e",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/o2OSpKzXuB1edCDyVC2MXAxXwyJ.jpg",
    genre_ids: [10749, 27, 53],
    id: 633802,
    original_language: "ru",
    original_title: "Приворот. Чёрное венчание",
    overview:
      "Terror strikes when a heartbroken woman uses black magic to get her husband back.",
    popularity: 235.484,
    poster_path:
      "https://image.tmdb.org/t/p/original/2AbGdSGlU6CpiV3lswHUgE5CdAA.jpg",
    release_date: "2021-02-11",
    title: "Dark Spell",
    video: false,
    vote_average: 6.7,
    vote_count: 95,
    category: "Romance",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "4e47a9d1-b898-4288-9d59-9589c2318a3c",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/6KgpxK3u4zOKLhTa16XNiYiDkJf.jpg",
    genre_ids: [99, 80],
    id: 933554,
    original_language: "en",
    original_title: "2000 Mules",
    overview:
      "True the Vote has been working with Dinesh D’Souza to create a bombshell movie that uses footage they obtained of ballot boxes in key states across America to steal the election in 2020.  100 Percent Fed Up reports – Using geo-tracking devices, True the Vote was able to take footage from drop boxes across America in key states like Georgia and others to track over 2,000 ‘mules” wearing gloves and disguises to stuff ballot boxes.",
    popularity: 616.061,
    poster_path:
      "https://image.tmdb.org/t/p/original/9UzHZdXIIIbixHIwGZCN9VqplVG.jpg",
    release_date: "2022-05-02",
    title: "2000 Mules",
    video: false,
    vote_average: 7.7,
    vote_count: 6,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "daa18d2a-05c0-4b4e-b944-33cce032b538",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/f2J8DpT5bqV0AiI9VVcfiuqKo5l.jpg",
    genre_ids: [35, 28, 99],
    id: 656663,
    original_language: "en",
    original_title: "Jackass Forever",
    overview:
      "Celebrate the joy of a perfectly executed shot to the groin as Johnny Knoxville, Steve-O and the rest of the gang return alongside some newcomers for one final round of hilarious, wildly absurd and often dangerous displays of stunts and comedy.",
    popularity: 420.947,
    poster_path:
      "https://image.tmdb.org/t/p/original/ugIdyvtAzHWOguD91UjHKoAvfum.jpg",
    release_date: "2022-02-01",
    title: "Jackass Forever",
    video: false,
    vote_average: 6.9,
    vote_count: 334,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "8904f0c6-bd78-4f6a-9b0e-1052ea49b6e7",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/nXH3PbWtH7qpWlaAwFCvvh40pk8.jpg",
    genre_ids: [99],
    id: 953300,
    original_language: "en",
    original_title: "The Mystery of Marilyn Monroe: The Unheard Tapes",
    overview:
      "This documentary explores the mystery surrounding the death of movie icon Marilyn Monroe through previously unheard interviews with her inner circle.",
    popularity: 206.135,
    poster_path:
      "https://image.tmdb.org/t/p/original/9Ab3MEngH2sWK8uydGBFfgZDB4z.jpg",
    release_date: "2022-04-27",
    title: "The Mystery of Marilyn Monroe: The Unheard Tapes",
    video: false,
    vote_average: 6.3,
    vote_count: 41,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "8904f0c6-bd78-4f6a-9b0e-1052ea49b6ea",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/8rft8A9nH43IReybFtYt21ezfMK.jpg",
    genre_ids: [99],
    id: 899082,
    original_language: "en",
    original_title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    overview:
      "An enchanting making-of story told through all-new in-depth interviews and cast conversations, inviting fans on a magical first-person journey through one of the most beloved film franchises of all time.",
    popularity: 134.839,
    poster_path:
      "https://image.tmdb.org/t/p/original/jntLBq0MLR3hrwKaTQswxACRPMs.jpg",
    release_date: "2022-01-01",
    title: "Harry Potter 20th Anniversary: Return to Hogwarts",
    video: false,
    vote_average: 7.8,
    vote_count: 1358,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "b1ce7adc-dc04-4cc9-9651-b2c1859976f9",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/l2Szl45c6YTszCqpNZVcU8b0M8P.jpg",
    genre_ids: [99],
    id: 662244,
    original_language: "en",
    original_title: "Fantastic Beasts: A Natural History",
    overview:
      "Stephen Fry embarks on a journey to discover the stories behind some of the world's most fantastic beasts that have inspired myths and legends in history, story-telling and film.",
    popularity: 104.742,
    poster_path:
      "https://image.tmdb.org/t/p/original/icqVeNNQPZ6vzQFirqcAHGchHCB.jpg",
    release_date: "2022-02-27",
    title: "Fantastic Beasts: A Natural History",
    video: false,
    vote_average: 6.9,
    vote_count: 11,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "a065ca1a-d2b8-4806-a4a2-ea1b3174a951",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/kxj8WaxRzxUcJn7LathZBDyN7Ys.jpg",
    genre_ids: [99],
    id: 927070,
    original_language: "en",
    original_title: "Polar Bear",
    overview:
      "Tells the story of a new mother whose memories of her own youth prepare her to navigate motherhood in the increasingly challenging world that polar bears face today.",
    popularity: 112.337,
    poster_path:
      "https://image.tmdb.org/t/p/original/nCRUQcbBs6Ix6YaBeCgC9OwE0mt.jpg",
    release_date: "2022-04-22",
    title: "Polar Bear",
    video: false,
    vote_average: 7.9,
    vote_count: 16,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "19b2f1c3-ccf3-4054-a93c-493bcae7c5ae",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/5dxftrwxnFHBkSKHJT3x1xwIydn.jpg",
    genre_ids: [99],
    id: 958080,
    original_language: "en",
    original_title: "Hold Your Breath: The Ice Dive",
    overview:
      "Follow free diver Johanna Nordblad in this documentary as she attempts to break the world record for distance traveled under ice with one breath.",
    popularity: 113.99,
    poster_path:
      "https://image.tmdb.org/t/p/original/5cm3Xk6zJcanO2mAZaAuNWyepGf.jpg",
    release_date: "2022-05-03",
    title: "Hold Your Breath: The Ice Dive",
    video: false,
    vote_average: 6.2,
    vote_count: 9,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "zd754a63-17cc-4e77-86ed-5cbb81236f37",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/slh9qCbyDcMN2rC9FiueZ6pR2fj.jpg",
    genre_ids: [99],
    id: 381749,
    original_language: "it",
    original_title: "Porno & Libertà",
    overview:
      "Italy, 1970. An increasing legion of harmless warriors begins a peaceful struggle for sexual freedom through pornography, shaking and shocking religious authorities and conservative political institutions. They are ironic, happy, crazy. They are dreamers, defenders of definitive communion between body and soul. But they were censored and humiliated. They were mistreated and arrested for demanding loud a new cultural renaissance.",
    popularity: 102.855,
    poster_path:
      "https://image.tmdb.org/t/p/original/xhB2hGJBSvK69ZDOZJvNnoGh9vL.jpg",
    release_date: "2016-06-24",
    title: "Porn to Be Free",
    video: false,
    vote_average: 5.5,
    vote_count: 67,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "086fb091-b216-4195-8289-0ebb1e0a1cc1",
    adult: false,
    backdrop_path: null,
    genre_ids: [99],
    id: 964943,
    original_language: "en",
    original_title: "Marvel Studios: Assembled – The Making of Moon Knight",
    overview:
      "Join the likes of Oscar Isaac and Ethan Hawke as they reveal how Marvel Studios' Moon Knight was painstakingly brought to life. Through insightful interviews with cast and crew, along with immersive footage from the set, this Making Of pulls back the curtain on this groundbreaking series. Additionally, incorporates a candid \"roundtable discussion\" with the series' directors.",
    popularity: 99.334,
    poster_path: null,
    release_date: "2022-05-25",
    title: "Marvel Studios: Assembled – The Making of Moon Knight",
    video: false,
    vote_average: 2,
    vote_count: 1,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
  {
    _id: "f124fa94-86d7-4334-8062-e4dbfaf75671",
    adult: false,
    backdrop_path:
      "https://image.tmdb.org/t/p/original/uO6ZUez70Twan92pqoV60T9kiGH.jpg",
    genre_ids: [99],
    id: 440249,
    original_language: "en",
    original_title: "After Porn Ends 2",
    overview:
      "After Porn Ends 2 picks up where its predecessor left off and not only turns back the clock to meet the oldest living stars in adult film's history, but goes in depth with some of Its most current retirees and juxtaposes their experiences in a life after porn. Delving deeper into society's ongoing stigmas of race, misogyny, and the reality of decreasing opportunities for these former VHS box cover stars. For some, their careers in adult entertainment is accepted proudly and without regret. In fact, it seems to have proven to be the pathway to their current happiness and inner peace. For others, however, a career in porn has proven to be a conduit to certain despair as they struggle to find a way to bury their past and emerge with a new career or calling.",
    popularity: 84.685,
    poster_path:
      "https://image.tmdb.org/t/p/original/rfItXrtDGILwsCdmgVxX79phFuI.jpg",
    release_date: "2017-03-28",
    title: "After Porn Ends 2",
    video: false,
    vote_average: 5.4,
    vote_count: 195,
    category: "Documentaries",
    liked: false,
    addedToWatchLater: false,
  },
];
